(() => {
  const apiBase = window.location.port === "8000" ? `${window.location.protocol}//${window.location.hostname}:8080/api/v1` : "/api/v1";
  async function api(path, options = {}) { const response = await fetch(`${apiBase}${path}`, { ...options, credentials: "include", headers: { Accept: "application/json", ...(options.headers || {}) } }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.error?.message || "API request failed"); return payload.data; }
  const esc = (value) => String(value ?? "").replace(/[&<>"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]));
  const filterStorageKey = "millena.superadmin.filters";
  const filterSelectors = ["#user-filter", "#user-status-filter", "#user-role-filter", "#plan-filter", "#plan-status-filter"];
  let allUsers = [], allPlans = [];
  function saveFilters() { localStorage.setItem(filterStorageKey, JSON.stringify(Object.fromEntries(filterSelectors.map(selector => [selector, document.querySelector(selector)?.value || ""])))); }
  function restoreFilters() { try { const filters = JSON.parse(localStorage.getItem(filterStorageKey) || "{}"); filterSelectors.forEach(selector => { const field = document.querySelector(selector); if (field && typeof filters[selector] === "string") field.value = filters[selector]; }); } catch { /* Ignore malformed browser storage. */ } }
  function renderSystem() { const needle=(document.querySelector("#user-filter")?.value||"").toLowerCase(), status=document.querySelector("#user-status-filter")?.value||"", role=document.querySelector("#user-role-filter")?.value||""; const users=allUsers.filter(u => (!needle || `${u.displayName} ${u.email}`.toLowerCase().includes(needle)) && (!status || u.status===status) && (!role || u.systemRole===role)); document.querySelector("#users-list").innerHTML = users.map(u => `<p><input data-user-select="${u.id}" type="checkbox"> <input data-user-name="${u.id}" value="${esc(u.displayName)}"> · ${esc(u.email)} · <select data-user-role="${u.id}"><option value="member" ${u.systemRole === "member" ? "selected" : ""}>member</option><option value="super_admin" ${u.systemRole === "super_admin" ? "selected" : ""}>super admin</option></select> <select data-user-status="${u.id}"><option value="active" ${u.status === "active" ? "selected" : ""}>active</option><option value="suspended" ${u.status === "suspended" ? "selected" : ""}>deaktiviran</option></select> <button data-save-user="${u.id}">Spremi</button></p>`).join("") || "Nema korisnika za odabrani filter."; const planNeedle=(document.querySelector("#plan-filter")?.value||"").toLowerCase(), planStatus=document.querySelector("#plan-status-filter")?.value||""; const plans=allPlans.filter(p => (!planNeedle || p.name.toLowerCase().includes(planNeedle)) && (!planStatus || (planStatus==="active")===p.isActive)); document.querySelector("#plans-list").innerHTML=plans.map(p=>`<p><input data-plan-name="${p.code}" value="${esc(p.name)}"> · <input data-plan-price="${p.code}" type="number" step="0.01" min="0" value="${(p.priceCents / 100).toFixed(2)}"> EUR · <input data-plan-limit="${p.code}" type="number" value="${p.monthlyPublicationLimit ?? ""}" placeholder="∞"> objava · <label><input data-plan-active="${p.code}" type="checkbox" ${p.isActive?"checked":""}> aktivan</label> <button data-save-plan="${p.code}" data-description="${esc(p.description)}">Spremi</button></p>`).join("") || "Nema paketa za odabrani filter."; }
  async function loadSystem() { [allUsers, allPlans] = await Promise.all([api("/system/users"), api("/system/plans")]); renderSystem(); }
  document.addEventListener("input", e => { if(e.target.matches("#user-filter,#plan-filter")){saveFilters();renderSystem();} }); document.addEventListener("change", e => { if(e.target.matches("#user-status-filter,#user-role-filter,#plan-status-filter")){saveFilters();renderSystem();} }); window.addEventListener("pagehide", saveFilters); document.addEventListener("click", async e => { const user=e.target.closest("[data-save-user]"); const plan=e.target.closest("[data-save-plan]"); if(e.target.closest("#select-visible")){document.querySelectorAll("[data-user-select]").forEach(x=>x.checked=true);return;} if(e.target.closest("#bulk-save")){const ids=[...document.querySelectorAll("[data-user-select]:checked")].map(x=>x.dataset.userSelect);if(!ids.length){alert("Odaberi barem jednog korisnika.");return;}try{await api("/system/users/bulk",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({userIds:ids,status:document.querySelector("#bulk-status").value})});await loadSystem();}catch(err){alert(err.message);}return;} try { if(user){await api(`/system/users/${user.dataset.saveUser}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({displayName:document.querySelector(`[data-user-name="${user.dataset.saveUser}"]`).value,status:document.querySelector(`[data-user-status="${user.dataset.saveUser}"]`).value,systemRole:document.querySelector(`[data-user-role="${user.dataset.saveUser}"]`).value})});} if(plan){const limit=document.querySelector(`[data-plan-limit="${plan.dataset.savePlan}"]`).value;await api(`/system/plans/${plan.dataset.savePlan}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:document.querySelector(`[data-plan-name="${plan.dataset.savePlan}"]`).value,description:plan.dataset.description,priceCents:Math.round(Number(document.querySelector(`[data-plan-price="${plan.dataset.savePlan}"]`).value)*100),monthlyPublicationLimit:limit?Number(limit):null,isActive:document.querySelector(`[data-plan-active="${plan.dataset.savePlan}"]`).checked})});} if(user||plan) await loadSystem();}catch(err){alert(err.message);} });
  async function boot() { try { const session = await api("/auth/me"); if (session?.user?.systemRole !== "super_admin") { window.location.replace("app.html"); return; } document.querySelector("#admin-name").textContent = session.user.displayName; document.querySelector("#admin-email").textContent = session.user.email; document.querySelector("#project-count").textContent = String(session.projects?.length || 0); document.querySelector("#api-status").textContent = "Online"; await loadSystem(); } catch { window.location.replace("login.html?next=superadmin.html"); } }
  restoreFilters(); document.querySelector("#logout")?.addEventListener("click", async () => { try { await api("/auth/logout", { method: "POST" }); } finally { window.location.replace("login.html"); } }); boot();
})();
