(() => {
  const apiBase = window.location.port === "8000" ? `${window.location.protocol}//${window.location.hostname}:8080/api/v1` : "/api/v1";
  async function api(path, options = {}) { const response = await fetch(`${apiBase}${path}`, { ...options, credentials: "include", headers: { Accept: "application/json", ...(options.headers || {}) } }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.error?.message || "API request failed"); return payload.data; }
  const esc = (value) => String(value ?? "").replace(/[&<>"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]));
  async function loadSystem() { const [users, plans] = await Promise.all([api("/system/users"), api("/system/plans")]); document.querySelector("#users-list").innerHTML = users.map(u => `<p><b>${esc(u.displayName)}</b> · ${esc(u.email)} · <select data-user-role="${u.id}"><option value="member" ${u.systemRole === "member" ? "selected" : ""}>member</option><option value="super_admin" ${u.systemRole === "super_admin" ? "selected" : ""}>super admin</option></select> <select data-user-status="${u.id}"><option value="active" ${u.status === "active" ? "selected" : ""}>active</option><option value="suspended" ${u.status === "suspended" ? "selected" : ""}>suspended</option></select> <button data-save-user="${u.id}" data-name="${esc(u.displayName)}">Spremi</button></p>`).join(""); document.querySelector("#plans-list").innerHTML = plans.map(p => `<p><b>${esc(p.name)}</b> · <input data-plan-price="${p.code}" type="number" value="${p.priceCents}"> centi · <input data-plan-limit="${p.code}" type="number" value="${p.monthlyPublicationLimit ?? ""}" placeholder="∞"> objava <button data-save-plan="${p.code}" data-name="${esc(p.name)}" data-description="${esc(p.description)}" data-active="${p.isActive}">Spremi</button></p>`).join(""); }
  document.addEventListener("click", async e => { const user=e.target.closest("[data-save-user]"); const plan=e.target.closest("[data-save-plan]"); try { if(user){await api(`/system/users/${user.dataset.saveUser}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({displayName:user.dataset.name,status:document.querySelector(`[data-user-status="${user.dataset.saveUser}"]`).value,systemRole:document.querySelector(`[data-user-role="${user.dataset.saveUser}"]`).value})});} if(plan){const limit=document.querySelector(`[data-plan-limit="${plan.dataset.savePlan}"]`).value;await api(`/system/plans/${plan.dataset.savePlan}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:plan.dataset.name,description:plan.dataset.description,priceCents:Number(document.querySelector(`[data-plan-price="${plan.dataset.savePlan}"]`).value),monthlyPublicationLimit:limit?Number(limit):null,isActive:plan.dataset.active==="true"})});} if(user||plan) await loadSystem();}catch(err){alert(err.message);} });
  async function boot() { try { const session = await api("/auth/me"); if (session?.user?.systemRole !== "super_admin") { window.location.replace("app.html"); return; } document.querySelector("#admin-name").textContent = session.user.displayName; document.querySelector("#admin-email").textContent = session.user.email; document.querySelector("#project-count").textContent = String(session.projects?.length || 0); document.querySelector("#api-status").textContent = "Online"; await loadSystem(); } catch { window.location.replace("login.html?next=superadmin.html"); } }
  document.querySelector("#logout")?.addEventListener("click", async () => { try { await api("/auth/logout", { method: "POST" }); } finally { window.location.replace("login.html"); } }); boot();
})();
